-- -- login
-- CREATE TABLE users ( username VARCHAR ( 256 ), PASSWORD VARCHAR ( 256 ), enabled BOOLEAN );
--
-- -- role
-- CREATE TABLE authorities ( username VARCHAR ( 256 ), authority VARCHAR ( 256 ) );
--
-- -- 기본 사용자 생성
-- INSERT INTO users ( username, PASSWORD, enabled ) VALUES ( 'user', '{noop}password', TRUE );
-- INSERT INTO users ( username, PASSWORD, enabled ) VALUES ( 'admin', '{bcrypt}$2a$10$wTlP9OtsXoTCVWbF11gn/uA3kjJ8Tj9gWMy0/P7hVNkwhvaYSowN2', TRUE );
--
-- -- 기본 role 생성
-- INSERT INTO authorities ( username, authority ) VALUES ( 'user', 'ROLE_USER' );
-- INSERT INTO authorities ( username, authority ) VALUES ( 'admin', 'ROLE_ADMIN' );